---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "rundeck-pv-mysql"
spec:
  capacity:
    storage: "3Gi"
  accessModes:
    - "ReadWriteMany"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-41dd9839::fsap-0579ed0ac909dcb74

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck-pv-claim-mysql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 3Gi
