---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "rundeck-pv-data"
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteMany"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-35c4814d::fsap-0e720sdfsdf

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck-pv-claim-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "rundeck-pv-logs"
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteMany"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-35c4814d::fsap-0b06sdfsdf01cef

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck-pv-claim-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi


---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "rundeck-pv-etc"
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteMany"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-35c4814d::fsap-00e4sdfsdff

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck-pv-claim-etc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
