---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "rundeck-pv-data"
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteMany"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: RUNDECK_EFS_ID::RUNDECK_EFS_ACCESSPOINT_DATA

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck-pv-claim-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "rundeck-pv-logs"
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteMany"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: RUNDECK_EFS_ID::RUNDECK_EFS_ACCESSPOINT_LOGS

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck-pv-claim-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
