apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rundeckpro
  namespace: default
  labels:
    app: rundeckpro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rundeckpro
  template:
    metadata:
      labels:
        app: rundeckpro
    spec:
      containers:
      - name: rundeck
        image: rundeckpro/enterprise:3.3.8
        env:
        - name: RUNDECK_GRAILS_URL
          value: "http://58c8349a-default-rundeckin-89de-245843308.us-east-2.elb.amazonaws.com"
        - name: RUNDECK_DATABASE_DRIVER
          value: "org.mariadb.jdbc.Driver"
        - name: RUNDECK_DATABASE_URL
          value: "jdbc:mysql://mysql.default.svc.cluster.local:3306/rundeckdb?autoReconnect=true&useSSL=false"
        - name: RUNDECK_DATABASE_USERNAME
          value: "rundeck"
        - name: RUNDECK_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-rundeckuser
              key: password
        - name: RUNDECK_PLUGIN_CLUSTER_HEARTBEAT_CONSIDERDEAD
          value: "120"
        - name: RUNDECK_PLUGIN_CLUSTER_AUTOTAKEOVER_SLEEP
          value: "10"
        - name: RUNDECK_PLUGIN_CLUSTER_REMOTEEXECUTION_ENABLED
          value: "false"
        ports:
        - containerPort: 4440
        volumeMounts:
          - name: data
            mountPath: /home/rundeck/server/data
          - name: logs
            mountPath: /home/rundeck/server/logs
          - name: license
            mountPath: /home/rundeck/etc/rundeckpro-license.key
            subPath: rundeckpro-license.key
          - name: acl 
            mountPath: /home/rundeck/etc/admin-role.aclpolicy
            subPath: admin-role.aclpolicy
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rundeck-pv-claim-data
      - name: logs
        persistentVolumeClaim:
          claimName: rundeck-pv-claim-logs
      - name: license
        secret:
          secretName: rundeckpro-license
          items:
          - key: rundeckpro-license.key
            path: rundeckpro-license.key
      - name: acl
        secret:
          secretName: rundeckpro-admin-acl
          items:
          - key: admin-role.aclpolicy
            path: admin-role.aclpolicy
